name: lfmtools
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.5.0=h27087fc_0
  - blosc=1.21.1=h83bc5f7_3
  - boost=1.78.0=py310hc4a4660_4
  - boost-cpp=1.78.0=h75c5d50_1
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.4.3=h7a311fb_0
  - ca-certificates=2022.9.24=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - contourpy=1.0.6=py310hbf28c38_0
  - curl=7.86.0=h2283fc2_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h5764c6d_1
  - dask-core=2022.11.0=pyhd8ed1ab_0
  - dav1d=1.0.0=h166bdaf_1
  - expat=2.5.0=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py310h5764c6d_1
  - fpocket=4.0.2=hbb826e7_0
  - freetype=2.12.1=hca18f0e_0
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h36c2ea0_2
  - greenlet=2.0.1=py310hd8f1fbe_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_100
  - icu=70.1=h27087fc_0
  - imagecodecs=2022.9.26=py310h90cd304_3
  - imageio=2.22.0=pyhfa7a67d_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.11.1=h5cdd6b5_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.86.0=h2283fc2_1
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.38=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.6.2=py310h8d5ebf3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h27087fc_1
  - networkx=2.8.8=pyhd8ed1ab_0
  - numpy=1.23.4=py310h53a5b5f_1
  - oddt=0.7=pyh500f238_0
  - openbabel=3.1.1=py310heaf86c6_5
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.7=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.1=py310h769672d_1
  - partd=1.3.0=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.2.0=py310h454ad03_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.21.0=py310hb8a676c_2
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.10.6=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.6=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_5
  - rdkit=2022.09.1=py310hb09c313_1
  - readline=8.1.2=h0f457ee_0
  - reportlab=3.5.68=py310h94fcab3_1
  - scikit-image=0.19.3=py310h769672d_2
  - scikit-learn=1.1.3=py310h0c3af53_1
  - setuptools=65.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_2
  - sqlalchemy=1.4.44=py310h5764c6d_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.10.10=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zfp=1.0.0=h27087fc_3
  - zlib=1.2.13=h166bdaf_4
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h6239696_4
  - pip:
    - altair==4.2.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - autodocktools-py3==1.5.7.post1+3.gaee55d5
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.5
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - commonmark==0.9.1
    - crem==0.2.9
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - gitdb==4.0.9
    - gitpython==3.1.29
    - htmlmin==0.1.12
    - idna==3.4
    - imagehash==4.3.1
    - importlib-metadata==5.0.0
    - ipykernel==6.17.1
    - ipyspeck==0.6.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.17.0
    - jupyter-client==7.4.7
    - jupyter-core==5.0.0
    - jupyter-packaging==0.12.3
    - jupyter-server==1.23.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - missingno==0.5.1
    - mistune==2.0.4
    - multimethod==1.9
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - pandas-profiling==3.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - phik==0.12.2
    - pickleshare==0.7.5
    - platformdirs==2.5.4
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py3dmol==1.8.1
    - pyarrow==10.0.0
    - pycparser==2.21
    - pydantic==1.10.2
    - pydeck==0.8.0
    - pygments==2.13.0
    - pympler==1.0.1
    - pyrsistent==0.19.2
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyzmq==24.0.1
    - requests==2.28.1
    - rich==12.6.0
    - scipy==1.9.3
    - seaborn==0.12.1
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - statsmodels==0.13.5
    - stmol==0.0.9
    - streamlit==1.15.0
    - streamlit-pandas-profiling==0.1.3
    - tangled-up-in-unicode==0.2.0
    - terminado==0.17.0
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomlkit==0.11.6
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typing-extensions==4.4.0
    - tzdata==2022.6
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - visions==0.7.5
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - widgetsnbextension==3.5.2
    - zipp==3.10.0
prefix: /home/patricio/anaconda3/envs/lfmtools
